spring:
  application:
    name: mybatis-plugin-tenant
  profiles:
    active: local
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml